namespace NachosMedia.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class seedgenres : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Genres VALUES (1 ,'ABSTRACT STRATEGY', 1)");
            Sql("INSERT INTO Genres VALUES (2 ,'ADVENTURE', 1)");
            Sql("INSERT INTO Genres VALUES (3 ,'CARD - TRADITIONAL', 1)");
            Sql("INSERT INTO Genres VALUES (4 ,'CITY BUILDING', 1)");
            Sql("INSERT INTO Genres VALUES (5 ,'CIVILIZATION', 1)");
            Sql("INSERT INTO Genres VALUES (6 ,'DEXTERITY', 1)");
            Sql("INSERT INTO Genres VALUES (7 ,'DICE', 1)");
            Sql("INSERT INTO Genres VALUES (8 ,'EDUCATIONAL', 1)");
            Sql("INSERT INTO Genres VALUES (9 ,'ELECTRONIC', 1)");
            Sql("INSERT INTO Genres VALUES (10 ,'EXPANSION', 1)");
            Sql("INSERT INTO Genres VALUES (11 ,'EXPLORATION', 1)");
            Sql("INSERT INTO Genres VALUES (12 ,'FAMILY', 1)");
            Sql("INSERT INTO Genres VALUES (13 ,'FANTASY', 1)");
            Sql("INSERT INTO Genres VALUES (14 ,'FIGHTING', 1)");
            Sql("INSERT INTO Genres VALUES (15 ,'HORROR', 1)");
            Sql("INSERT INTO Genres VALUES (16 ,'MATHEMATICS', 1)");
            Sql("INSERT INTO Genres VALUES (17 ,'MAZE', 1)");
            Sql("INSERT INTO Genres VALUES (18 ,'MEMORY', 1)");
            Sql("INSERT INTO Genres VALUES (19 ,'MURDER/MYSTERY', 1)");
            Sql("INSERT INTO Genres VALUES (20 ,'PARTY', 1)");
            Sql("INSERT INTO Genres VALUES (21 ,'POLITICAL', 1)");
            Sql("INSERT INTO Genres VALUES (22 ,'POP CULTURE', 1)");
            Sql("INSERT INTO Genres VALUES (23 ,'PUZZLE - JIGSAW', 1)");
            Sql("INSERT INTO Genres VALUES (24 ,'PUZZLE - OTHER', 1)");
            Sql("INSERT INTO Genres VALUES (25 ,'RACING', 1)");
            Sql("INSERT INTO Genres VALUES (26 ,'SCI-FI', 1)");
            Sql("INSERT INTO Genres VALUES (27 ,'SIMULATION - ECONOMIC', 1)");
            Sql("INSERT INTO Genres VALUES (28 ,'SIMULATION - OTHER', 1)");
            Sql("INSERT INTO Genres VALUES (29 ,'SIMULATION - WAR', 1)");
            Sql("INSERT INTO Genres VALUES (30 ,'TRIVIA', 1)");
            Sql("INSERT INTO Genres VALUES (31 ,'ZOMBIES', 1)");
            Sql("INSERT INTO Genres VALUES (32 ,'ACTION', 2)");
            Sql("INSERT INTO Genres VALUES (33 ,'ADVENTURE', 2)");
            Sql("INSERT INTO Genres VALUES (34 ,'ART', 2)");
            Sql("INSERT INTO Genres VALUES (35 ,'BIOGRAPHY', 2)");
            Sql("INSERT INTO Genres VALUES (36 ,'BUSINESS', 2)");
            Sql("INSERT INTO Genres VALUES (37 ,'CHILDRENS', 2)");
            Sql("INSERT INTO Genres VALUES (38 ,'CLASSICS', 2)");
            Sql("INSERT INTO Genres VALUES (39 ,'COMEDY', 2)");
            Sql("INSERT INTO Genres VALUES (40 ,'COMPUTERS & TECHNOLOGY', 2)");
            Sql("INSERT INTO Genres VALUES (41 ,'CONTEMPORARY', 2)");
            Sql("INSERT INTO Genres VALUES (42 ,'COOKING', 2)");
            Sql("INSERT INTO Genres VALUES (43 ,'CRAFTS', 2)");
            Sql("INSERT INTO Genres VALUES (44 ,'EDUCATION REFERENCE', 2)");
            Sql("INSERT INTO Genres VALUES (45 ,'FANTASY', 2)");
            Sql("INSERT INTO Genres VALUES (46 ,'FICTION', 2)");
            Sql("INSERT INTO Genres VALUES (47 ,'HEALTH & FITNESS', 2)");
            Sql("INSERT INTO Genres VALUES (48 ,'HEALTH & MEDICINE', 2)");
            Sql("INSERT INTO Genres VALUES (49 ,'HISTORICAL FICTION', 2)");
            Sql("INSERT INTO Genres VALUES (50 ,'HISTORY', 2)");
            Sql("INSERT INTO Genres VALUES (51 ,'HOBBIES', 2)");
            Sql("INSERT INTO Genres VALUES (52 ,'HOME & GARDEN', 2)");
            Sql("INSERT INTO Genres VALUES (53 ,'HORROR', 2)");
            Sql("INSERT INTO Genres VALUES (54 ,'HUMOR', 2)");
            Sql("INSERT INTO Genres VALUES (55 ,'LITERATURE', 2)");
            Sql("INSERT INTO Genres VALUES (56 ,'MYSTERY', 2)");
            Sql("INSERT INTO Genres VALUES (57 ,'NON-FICTION', 2)");
            Sql("INSERT INTO Genres VALUES (58 ,'PROGRAMMING', 2)");
            Sql("INSERT INTO Genres VALUES (59 ,'RELIGION & SPIRITUALITY', 2)");
            Sql("INSERT INTO Genres VALUES (60 ,'ROMANCE', 2)");
            Sql("INSERT INTO Genres VALUES (61 ,'SCIENCE', 2)");
            Sql("INSERT INTO Genres VALUES (62 ,'SCI-FI', 2)");
            Sql("INSERT INTO Genres VALUES (63 ,'SELF-HELP', 2)");
            Sql("INSERT INTO Genres VALUES (64 ,'TEXTBOOK', 2)");
            Sql("INSERT INTO Genres VALUES (65 ,'THRILLER', 2)");
            Sql("INSERT INTO Genres VALUES (66 ,'WESTERN', 2)");
            Sql("INSERT INTO Genres VALUES (67 ,'YOUNG ADULT', 2)");
            Sql("INSERT INTO Genres VALUES (68 ,'OTHER', 2)");
            Sql("INSERT INTO Genres VALUES (69 ,'ACTION/ADVENTURE', 3)");
            Sql("INSERT INTO Genres VALUES (70 ,'ANIME', 3)");
            Sql("INSERT INTO Genres VALUES (71 ,'CRIME', 3)");
            Sql("INSERT INTO Genres VALUES (72 ,'DRAMA', 3)");
            Sql("INSERT INTO Genres VALUES (73 ,'FANTASY', 3)");
            Sql("INSERT INTO Genres VALUES (74 ,'HISTORICAL FICTION', 3)");
            Sql("INSERT INTO Genres VALUES (75 ,'HORROR', 3)");
            Sql("INSERT INTO Genres VALUES (76 ,'MANGA', 3)");
            Sql("INSERT INTO Genres VALUES (77 ,'REAL-LIFE', 3)");
            Sql("INSERT INTO Genres VALUES (78 ,'SCI-FI', 3)");
            Sql("INSERT INTO Genres VALUES (79 ,'SUPER HERO', 3)");
            Sql("INSERT INTO Genres VALUES (80 ,'OTHER', 3)");
            Sql("INSERT INTO Genres VALUES (81 ,'ACTION', 4)");
            Sql("INSERT INTO Genres VALUES (82 ,'ADVENTURE', 4)");
            Sql("INSERT INTO Genres VALUES (83 ,'ANIMATION', 4)");
            Sql("INSERT INTO Genres VALUES (84 ,'ANIME', 4)");
            Sql("INSERT INTO Genres VALUES (85 ,'BIOGRAPHY', 4)");
            Sql("INSERT INTO Genres VALUES (86 ,'COMEDY', 4)");
            Sql("INSERT INTO Genres VALUES (87 ,'CONCERTS', 4)");
            Sql("INSERT INTO Genres VALUES (88 ,'CRIME', 4)");
            Sql("INSERT INTO Genres VALUES (89 ,'DOCUMENTARY', 4)");
            Sql("INSERT INTO Genres VALUES (90 ,'DRAMA', 4)");
            Sql("INSERT INTO Genres VALUES (91 ,'FAMILY', 4)");
            Sql("INSERT INTO Genres VALUES (92 ,'FANTASY', 4)");
            Sql("INSERT INTO Genres VALUES (93 ,'FILM NOIR', 4)");
            Sql("INSERT INTO Genres VALUES (94 ,'HORROR', 4)");
            Sql("INSERT INTO Genres VALUES (95 ,'MUSICAL', 4)");
            Sql("INSERT INTO Genres VALUES (96 ,'MYSTERY', 4)");
            Sql("INSERT INTO Genres VALUES (97 ,'ROMANCE', 4)");
            Sql("INSERT INTO Genres VALUES (98 ,'SCI-FI', 4)");
            Sql("INSERT INTO Genres VALUES (99 ,'SHORT FILM', 4)");
            Sql("INSERT INTO Genres VALUES (100 ,'SPORTS', 4)");
            Sql("INSERT INTO Genres VALUES (101 ,'SPECIAL INTERESTS', 4)");
            Sql("INSERT INTO Genres VALUES (102 ,'THRILLER', 4)");
            Sql("INSERT INTO Genres VALUES (103 ,'WAR', 4)");
            Sql("INSERT INTO Genres VALUES (104 ,'WESTERN', 4)");
            Sql("INSERT INTO Genres VALUES (105 ,'OTHER', 4)");
            Sql("INSERT INTO Genres VALUES (106 ,'ALTERNATIVE', 5)");
            Sql("INSERT INTO Genres VALUES (107 ,'ALT-COUNTRY', 5)");
            Sql("INSERT INTO Genres VALUES (108 ,'BLUES', 5)");
            Sql("INSERT INTO Genres VALUES (109 ,'CLASSIC ROCK', 5)");
            Sql("INSERT INTO Genres VALUES (110 ,'CLASSICAL', 5)");
            Sql("INSERT INTO Genres VALUES (111 ,'COMEDY', 5)");
            Sql("INSERT INTO Genres VALUES (112 ,'COUNTRY', 5)");
            Sql("INSERT INTO Genres VALUES (113 ,'DANCE', 5)");
            Sql("INSERT INTO Genres VALUES (114 ,'EASY LISTENING', 5)");
            Sql("INSERT INTO Genres VALUES (115 ,'ELECTRONIC', 5)");
            Sql("INSERT INTO Genres VALUES (116 ,'HIP HOP', 5)");
            Sql("INSERT INTO Genres VALUES (117 ,'INDIE POP', 5)");
            Sql("INSERT INTO Genres VALUES (118 ,'INDIE ROCK', 5)");
            Sql("INSERT INTO Genres VALUES (119 ,'INSPIRATIONAL', 5)");
            Sql("INSERT INTO Genres VALUES (120 ,'JAZZ', 5)");
            Sql("INSERT INTO Genres VALUES (121 ,'LATIN', 5)");
            Sql("INSERT INTO Genres VALUES (122 ,'METAL', 5)");
            Sql("INSERT INTO Genres VALUES (123 ,'NEW AGE', 5)");
            Sql("INSERT INTO Genres VALUES (124 ,'POP', 5)");
            Sql("INSERT INTO Genres VALUES (125 ,'PUNK', 5)");
            Sql("INSERT INTO Genres VALUES (126 ,'R&B', 5)");
            Sql("INSERT INTO Genres VALUES (127 ,'RAP', 5)");
            Sql("INSERT INTO Genres VALUES (128 ,'REGGAE', 5)");
            Sql("INSERT INTO Genres VALUES (129 ,'SOUL', 5)");
            Sql("INSERT INTO Genres VALUES (130 ,'ROCK', 5)");
            Sql("INSERT INTO Genres VALUES (131 ,'SINGER/SONGWRITER', 5)");
            Sql("INSERT INTO Genres VALUES (132 ,'OTHER', 5)");
            Sql("INSERT INTO Genres VALUES (133 ,'ACTION', 6)");
            Sql("INSERT INTO Genres VALUES (134 ,'ADVENTURE', 6)");
            Sql("INSERT INTO Genres VALUES (135 ,'ANIMATION', 6)");
            Sql("INSERT INTO Genres VALUES (136 ,'ANIME', 6)");
            Sql("INSERT INTO Genres VALUES (137 ,'CARTOONS', 6)");
            Sql("INSERT INTO Genres VALUES (138 ,'COMEDY', 6)");
            Sql("INSERT INTO Genres VALUES (139 ,'COOKING', 6)");
            Sql("INSERT INTO Genres VALUES (140 ,'CRIME', 6)");
            Sql("INSERT INTO Genres VALUES (141 ,'DOCUMENTARY', 6)");
            Sql("INSERT INTO Genres VALUES (142 ,'DRAMA', 6)");
            Sql("INSERT INTO Genres VALUES (143 ,'EDUCATIONAL', 6)");
            Sql("INSERT INTO Genres VALUES (144 ,'FAMILY', 6)");
            Sql("INSERT INTO Genres VALUES (145 ,'FANTASY', 6)");
            Sql("INSERT INTO Genres VALUES (146 ,'HORROR', 6)");
            Sql("INSERT INTO Genres VALUES (147 ,'INTERVIEWS', 6)");
            Sql("INSERT INTO Genres VALUES (148 ,'MEDICAL', 6)");
            Sql("INSERT INTO Genres VALUES (149 ,'MUSIC', 6)");
            Sql("INSERT INTO Genres VALUES (150 ,'MYSTERY', 6)");
            Sql("INSERT INTO Genres VALUES (151 ,'NEWS', 6)");
            Sql("INSERT INTO Genres VALUES (152 ,'POLITICS', 6)");
            Sql("INSERT INTO Genres VALUES (153 ,'REALITY TV', 6)");
            Sql("INSERT INTO Genres VALUES (154 ,'ROMANCE', 6)");
            Sql("INSERT INTO Genres VALUES (155 ,'SCI-FI', 6)");
            Sql("INSERT INTO Genres VALUES (156 ,'SOAPS', 6)");
            Sql("INSERT INTO Genres VALUES (157 ,'SPORTS', 6)");
            Sql("INSERT INTO Genres VALUES (158 ,'SPECIAL INTERESTS', 6)");
            Sql("INSERT INTO Genres VALUES (159 ,'TALK SHOW', 6)");
            Sql("INSERT INTO Genres VALUES (160 ,'THRILLER', 6)");
            Sql("INSERT INTO Genres VALUES (161 ,'WAR', 6)");
            Sql("INSERT INTO Genres VALUES (162 ,'WESTERN', 6)");
            Sql("INSERT INTO Genres VALUES (163 ,'WILDLIFE', 6)");
            Sql("INSERT INTO Genres VALUES (164 ,'OTHER', 6)");
            Sql("INSERT INTO Genres VALUES (165 ,'ACTION/ADVENTURE', 7)");
            Sql("INSERT INTO Genres VALUES (166 ,'ACTION RPG', 7)");
            Sql("INSERT INTO Genres VALUES (167 ,'BOARD/CARD GAME', 7)");
            Sql("INSERT INTO Genres VALUES (168 ,'CONSTRUCTION SIM', 7)");
            Sql("INSERT INTO Genres VALUES (169 ,'FANTASY', 7)");
            Sql("INSERT INTO Genres VALUES (170 ,'FIGHTING', 7)");
            Sql("INSERT INTO Genres VALUES (171 ,'GRAPHIC ADVENTURE', 7)");
            Sql("INSERT INTO Genres VALUES (172 ,'LIFE SIMULATION', 7)");
            Sql("INSERT INTO Genres VALUES (173 ,'METROIDVANIA', 7)");
            Sql("INSERT INTO Genres VALUES (174 ,'MMORPG', 7)");
            Sql("INSERT INTO Genres VALUES (175 ,'MMORTS', 7)");
            Sql("INSERT INTO Genres VALUES (176 ,'MUSIC', 7)");
            Sql("INSERT INTO Genres VALUES (177 ,'PARTY', 7)");
            Sql("INSERT INTO Genres VALUES (178 ,'PLATFORM', 7)");
            Sql("INSERT INTO Genres VALUES (179 ,'RACING', 7)");
            Sql("INSERT INTO Genres VALUES (180 ,'ROGUELIKE', 7)");
            Sql("INSERT INTO Genres VALUES (181 ,'SHOOTER', 7)");
            Sql("INSERT INTO Genres VALUES (182 ,'SPORTS', 7)");
            Sql("INSERT INTO Genres VALUES (183 ,'STEALTH', 7)");
            Sql("INSERT INTO Genres VALUES (184 ,'STRATEGY', 7)");
            Sql("INSERT INTO Genres VALUES (185 ,'SURVIVAL/HORROR', 7)");
            Sql("INSERT INTO Genres VALUES (186 ,'TEXT ADVENTURE', 7)");
            Sql("INSERT INTO Genres VALUES (187 ,'TOWER DEFENSE', 7)");
            Sql("INSERT INTO Genres VALUES (188 ,'TRIVIA', 7)");
            Sql("INSERT INTO Genres VALUES (189 ,'TURN-BASED STRATEGY', 7)");
            Sql("INSERT INTO Genres VALUES (190 ,'VEHICLE SIMULATION', 7)");
            Sql("INSERT INTO Genres VALUES (191 ,'WARGAME', 7)");
            Sql("INSERT INTO Genres VALUES (192 ,'OTHER', 7)");
            Sql("INSERT INTO Genres VALUES (193 ,'OTHER', 1)");
        }
        
        public override void Down()
        {
        }
    }
}
