// <auto-generated />
namespace NachosMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifycategoryformatgenreforfks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifycategoryformatgenreforfks));
        
        string IMigrationMetadata.Id
        {
            get { return "201606042117142_modify-category-format-genre-for-fks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
